# Generated by Django 3.0.6 on 2020-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200610_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(default='k@k.com', max_length=100),
            preserve_default=False,
        ),
    ]
